name = "dreamysuite"
main = "workers/app.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[assets]
directory = "./build/client"

[vars]
APP_URL = "https://dreamysuite.com"

[[routes]]
pattern = "dreamysuite.com"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "dreamysuite-db"
database_id = "db07b9de-1e33-4b16-af0b-df7e4e444a54"

[[kv_namespaces]]
binding = "KV"
id = "8fb116b82a3f4b5d8de3195ebe28df04"
preview_id = "8fb116b82a3f4b5d8de3195ebe28df04"

[[r2_buckets]]
binding = "R2"
bucket_name = "dreamysuite-assets"
