import type { EffectEntry } from "./types";

export const BACKGROUND_EFFECTS: EffectEntry[] = [
  {
    id: "aurora",
    name: "Aurora",
    source: "reactbits",
    category: "background",
    mood: ["dramatic", "whimsical"],
    eventTypes: ["wedding", "anniversary", "elopement"],
    intensity: "medium",
    description: "Flowing aurora borealis light ribbons",
  },
  {
    id: "balatro",
    name: "Balatro",
    source: "reactbits",
    category: "background",
    mood: ["playful", "dramatic"],
    eventTypes: ["celebration", "engagement"],
    intensity: "dramatic",
    description: "Psychedelic swirling color distortion",
  },
  {
    id: "ballpit",
    name: "Ballpit",
    source: "reactbits",
    category: "background",
    mood: ["playful"],
    eventTypes: ["engagement", "celebration"],
    intensity: "dramatic",
    description: "Interactive 3D ball physics simulation",
  },
  {
    id: "beams",
    name: "Beams",
    source: "reactbits",
    category: "background",
    mood: ["elegant", "dramatic"],
    eventTypes: ["wedding", "elopement", "celebration"],
    intensity: "medium",
    description: "Converging light beams from above",
  },
  {
    id: "color-bends",
    name: "ColorBends",
    source: "reactbits",
    category: "background",
    mood: ["modern", "playful"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Bending color gradients that shift on scroll",
  },
  {
    id: "dark-veil",
    name: "DarkVeil",
    source: "reactbits",
    category: "background",
    mood: ["dramatic", "elegant"],
    eventTypes: ["elopement", "anniversary"],
    intensity: "subtle",
    description: "Dark atmospheric fog overlay",
  },
  {
    id: "dither",
    name: "Dither",
    source: "reactbits",
    category: "background",
    mood: ["modern"],
    eventTypes: ["engagement", "elopement"],
    intensity: "subtle",
    description: "Retro dithering pattern with gradient",
  },
  {
    id: "dot-field",
    name: "DotField",
    source: "reactbits",
    category: "background",
    mood: ["modern", "elegant"],
    eventTypes: "*",
    intensity: "subtle",
    description: "Field of animated dots reacting to cursor",
  },
  {
    id: "evil-eye",
    name: "EvilEye",
    source: "reactbits",
    category: "background",
    mood: ["dramatic", "whimsical"],
    eventTypes: ["celebration"],
    intensity: "dramatic",
    description: "Animated eye that follows cursor movement",
  },
  {
    id: "faulty-terminal",
    name: "FaultyTerminal",
    source: "reactbits",
    category: "background",
    mood: ["modern", "dramatic"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Glitchy terminal screen with scan lines",
  },
  {
    id: "floating-lines",
    name: "FloatingLines",
    source: "reactbits",
    category: "background",
    mood: ["elegant", "romantic"],
    eventTypes: ["wedding", "vow-renewal", "anniversary"],
    intensity: "subtle",
    description: "Gently drifting minimal line patterns",
  },
  {
    id: "galaxy",
    name: "Galaxy",
    source: "reactbits",
    category: "background",
    mood: ["dramatic", "whimsical"],
    eventTypes: ["elopement", "celebration"],
    intensity: "dramatic",
    description: "Deep space galaxy with swirling stars",
  },
  {
    id: "gradient-blinds",
    name: "GradientBlinds",
    source: "reactbits",
    category: "background",
    mood: ["modern", "elegant"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Animated gradient blinds transition effect",
  },
  {
    id: "grainient",
    name: "Grainient",
    source: "reactbits",
    category: "background",
    mood: ["elegant", "romantic"],
    eventTypes: ["anniversary", "wedding", "vow-renewal"],
    intensity: "subtle",
    description: "Warm grainy gradient with film texture",
  },
  {
    id: "grid-distortion",
    name: "GridDistortion",
    source: "reactbits",
    category: "background",
    mood: ["modern", "dramatic"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Grid that warps and distorts on interaction",
  },
  {
    id: "grid-motion",
    name: "GridMotion",
    source: "reactbits",
    category: "background",
    mood: ["modern", "playful"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Animated grid cells with shifting images",
  },
  {
    id: "grid-scan",
    name: "GridScan",
    source: "reactbits",
    category: "background",
    mood: ["modern", "dramatic"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Scanning beam sweeps over a grid pattern",
  },
  {
    id: "hyperspeed",
    name: "Hyperspeed",
    source: "reactbits",
    category: "background",
    mood: ["dramatic", "modern"],
    eventTypes: ["celebration", "engagement"],
    intensity: "dramatic",
    description: "Star-field warp speed tunnel effect",
  },
  {
    id: "iridescence",
    name: "Iridescence",
    source: "reactbits",
    category: "background",
    mood: ["romantic", "whimsical"],
    eventTypes: ["wedding", "engagement", "vow-renewal"],
    intensity: "medium",
    description: "Shimmering iridescent color surface",
  },
  {
    id: "letter-glitch",
    name: "LetterGlitch",
    source: "reactbits",
    category: "background",
    mood: ["modern", "dramatic"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Glitching letter matrix background",
  },
  {
    id: "light-pillar",
    name: "LightPillar",
    source: "reactbits",
    category: "background",
    mood: ["dramatic", "elegant"],
    eventTypes: ["elopement", "wedding", "anniversary"],
    intensity: "medium",
    description: "Vertical pillars of light rising upward",
  },
  {
    id: "light-rays",
    name: "LightRays",
    source: "reactbits",
    category: "background",
    mood: ["romantic", "dramatic"],
    eventTypes: ["wedding", "elopement"],
    intensity: "medium",
    description: "Volumetric god rays filtering through",
  },
  {
    id: "lightning",
    name: "Lightning",
    source: "reactbits",
    category: "background",
    mood: ["dramatic"],
    eventTypes: ["celebration", "elopement"],
    intensity: "dramatic",
    description: "Electric lightning strikes and arcs",
  },
  {
    id: "line-waves",
    name: "LineWaves",
    source: "reactbits",
    category: "background",
    mood: ["elegant", "modern"],
    eventTypes: ["elopement", "wedding", "anniversary"],
    intensity: "subtle",
    description: "Flowing wave lines in gentle motion",
  },
  {
    id: "liquid-chrome",
    name: "LiquidChrome",
    source: "reactbits",
    category: "background",
    mood: ["modern", "dramatic"],
    eventTypes: ["engagement", "celebration"],
    intensity: "dramatic",
    description: "Liquid metal chrome surface reflections",
  },
  {
    id: "liquid-ether",
    name: "LiquidEther",
    source: "reactbits",
    category: "background",
    mood: ["romantic", "whimsical"],
    eventTypes: ["anniversary", "wedding", "vow-renewal"],
    intensity: "medium",
    description: "Slow-moving ethereal liquid color blending",
  },
  {
    id: "orb",
    name: "Orb",
    source: "reactbits",
    category: "background",
    mood: ["whimsical", "romantic"],
    eventTypes: ["wedding", "engagement"],
    intensity: "medium",
    description: "Glowing orb of light with soft halo",
  },
  {
    id: "particles",
    name: "Particles",
    source: "reactbits",
    category: "background",
    mood: ["playful", "whimsical"],
    eventTypes: ["engagement", "celebration", "wedding"],
    intensity: "medium",
    description: "Floating particle field with gentle drift",
  },
  {
    id: "pixel-blast",
    name: "PixelBlast",
    source: "reactbits",
    category: "background",
    mood: ["playful", "dramatic"],
    eventTypes: ["celebration", "engagement"],
    intensity: "dramatic",
    description: "Exploding pixel burst animation",
  },
  {
    id: "pixel-snow",
    name: "PixelSnow",
    source: "reactbits",
    category: "background",
    mood: ["whimsical", "playful"],
    eventTypes: ["wedding", "celebration"],
    intensity: "subtle",
    description: "Gentle falling pixel snowflakes",
  },
  {
    id: "plasma",
    name: "Plasma",
    source: "reactbits",
    category: "background",
    mood: ["dramatic", "modern"],
    eventTypes: ["celebration", "engagement"],
    intensity: "dramatic",
    description: "Pulsing plasma energy field",
  },
  {
    id: "plasma-wave",
    name: "PlasmaWave",
    source: "reactbits",
    category: "background",
    mood: ["dramatic", "modern"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Undulating plasma wave ripples",
  },
  {
    id: "prism",
    name: "Prism",
    source: "reactbits",
    category: "background",
    mood: ["elegant", "modern"],
    eventTypes: ["wedding", "engagement"],
    intensity: "medium",
    description: "Light refraction through prismatic surface",
  },
  {
    id: "prismatic-burst",
    name: "PrismaticBurst",
    source: "reactbits",
    category: "background",
    mood: ["playful", "dramatic"],
    eventTypes: ["celebration", "engagement"],
    intensity: "dramatic",
    description: "Rainbow prismatic light explosion",
  },
  {
    id: "radar",
    name: "Radar",
    source: "reactbits",
    category: "background",
    mood: ["modern"],
    eventTypes: ["celebration"],
    intensity: "subtle",
    description: "Rotating radar sweep with blips",
  },
  {
    id: "ripple-grid",
    name: "RippleGrid",
    source: "reactbits",
    category: "background",
    mood: ["modern", "elegant"],
    eventTypes: "*",
    intensity: "subtle",
    description: "Grid with ripple wave propagation",
  },
  {
    id: "shape-grid",
    name: "ShapeGrid",
    source: "reactbits",
    category: "background",
    mood: ["modern", "playful"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Grid of animated geometric shapes",
  },
  {
    id: "silk",
    name: "Silk",
    source: "reactbits",
    category: "background",
    mood: ["romantic", "elegant"],
    eventTypes: ["wedding", "vow-renewal", "anniversary"],
    intensity: "subtle",
    description: "Flowing silk fabric in gentle motion",
  },
  {
    id: "soft-aurora",
    name: "SoftAurora",
    source: "reactbits",
    category: "background",
    mood: ["romantic", "whimsical"],
    eventTypes: ["wedding", "vow-renewal"],
    intensity: "subtle",
    description: "Soft pastel aurora light wash",
  },
  {
    id: "threads",
    name: "Threads",
    source: "reactbits",
    category: "background",
    mood: ["elegant", "romantic"],
    eventTypes: ["wedding", "anniversary"],
    intensity: "subtle",
    description: "Delicate interwoven thread animation",
  },
  {
    id: "waves",
    name: "Waves",
    source: "reactbits",
    category: "background",
    mood: ["elegant", "romantic"],
    eventTypes: ["wedding", "elopement", "anniversary"],
    intensity: "subtle",
    description: "Smooth ocean-like wave undulation",
  },
];
