import type { EffectEntry, EffectCategory, EventType } from "./types";

export const EFFECT_REGISTRY: EffectEntry[] = [
  // ═══════════════════════════════════════════
  // BACKGROUNDS (42)
  // ═══════════════════════════════════════════
  {
    id: "aurora",
    name: "Aurora",
    source: "reactbits",
    category: "background",
    mood: ["dramatic", "whimsical"],
    eventTypes: ["wedding", "anniversary", "elopement"],
    intensity: "medium",
    description: "Flowing aurora borealis light ribbons",
  },
  {
    id: "balatro",
    name: "Balatro",
    source: "reactbits",
    category: "background",
    mood: ["playful", "dramatic"],
    eventTypes: ["celebration", "engagement"],
    intensity: "dramatic",
    description: "Psychedelic swirling color distortion",
  },
  {
    id: "ballpit",
    name: "Ballpit",
    source: "reactbits",
    category: "background",
    mood: ["playful"],
    eventTypes: ["engagement", "celebration"],
    intensity: "dramatic",
    description: "Interactive 3D ball physics simulation",
  },
  {
    id: "beams",
    name: "Beams",
    source: "reactbits",
    category: "background",
    mood: ["elegant", "dramatic"],
    eventTypes: ["wedding", "elopement", "celebration"],
    intensity: "medium",
    description: "Converging light beams from above",
  },
  {
    id: "color-bends",
    name: "ColorBends",
    source: "reactbits",
    category: "background",
    mood: ["modern", "playful"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Bending color gradients that shift on scroll",
  },
  {
    id: "dark-veil",
    name: "DarkVeil",
    source: "reactbits",
    category: "background",
    mood: ["dramatic", "elegant"],
    eventTypes: ["elopement", "anniversary"],
    intensity: "subtle",
    description: "Dark atmospheric fog overlay",
  },
  {
    id: "dither",
    name: "Dither",
    source: "reactbits",
    category: "background",
    mood: ["modern"],
    eventTypes: ["engagement", "elopement"],
    intensity: "subtle",
    description: "Retro dithering pattern with gradient",
  },
  {
    id: "dot-field",
    name: "DotField",
    source: "reactbits",
    category: "background",
    mood: ["modern", "elegant"],
    eventTypes: "*",
    intensity: "subtle",
    description: "Field of animated dots reacting to cursor",
  },
  {
    id: "evil-eye",
    name: "EvilEye",
    source: "reactbits",
    category: "background",
    mood: ["dramatic", "whimsical"],
    eventTypes: ["celebration"],
    intensity: "dramatic",
    description: "Animated eye that follows cursor movement",
  },
  {
    id: "faulty-terminal",
    name: "FaultyTerminal",
    source: "reactbits",
    category: "background",
    mood: ["modern", "dramatic"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Glitchy terminal screen with scan lines",
  },
  {
    id: "floating-lines",
    name: "FloatingLines",
    source: "reactbits",
    category: "background",
    mood: ["elegant", "romantic"],
    eventTypes: ["wedding", "vow-renewal", "anniversary"],
    intensity: "subtle",
    description: "Gently drifting minimal line patterns",
  },
  {
    id: "galaxy",
    name: "Galaxy",
    source: "reactbits",
    category: "background",
    mood: ["dramatic", "whimsical"],
    eventTypes: ["elopement", "celebration"],
    intensity: "dramatic",
    description: "Deep space galaxy with swirling stars",
  },
  {
    id: "gradient-blinds",
    name: "GradientBlinds",
    source: "reactbits",
    category: "background",
    mood: ["modern", "elegant"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Animated gradient blinds transition effect",
  },
  {
    id: "grainient",
    name: "Grainient",
    source: "reactbits",
    category: "background",
    mood: ["elegant", "romantic"],
    eventTypes: ["anniversary", "wedding", "vow-renewal"],
    intensity: "subtle",
    description: "Warm grainy gradient with film texture",
  },
  {
    id: "grid-distortion",
    name: "GridDistortion",
    source: "reactbits",
    category: "background",
    mood: ["modern", "dramatic"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Grid that warps and distorts on interaction",
  },
  {
    id: "grid-motion",
    name: "GridMotion",
    source: "reactbits",
    category: "background",
    mood: ["modern", "playful"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Animated grid cells with shifting images",
  },
  {
    id: "grid-scan",
    name: "GridScan",
    source: "reactbits",
    category: "background",
    mood: ["modern", "dramatic"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Scanning beam sweeps over a grid pattern",
  },
  {
    id: "hyperspeed",
    name: "Hyperspeed",
    source: "reactbits",
    category: "background",
    mood: ["dramatic", "modern"],
    eventTypes: ["celebration", "engagement"],
    intensity: "dramatic",
    description: "Star-field warp speed tunnel effect",
  },
  {
    id: "iridescence",
    name: "Iridescence",
    source: "reactbits",
    category: "background",
    mood: ["romantic", "whimsical"],
    eventTypes: ["wedding", "engagement", "vow-renewal"],
    intensity: "medium",
    description: "Shimmering iridescent color surface",
  },
  {
    id: "letter-glitch",
    name: "LetterGlitch",
    source: "reactbits",
    category: "background",
    mood: ["modern", "dramatic"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Glitching letter matrix background",
  },
  {
    id: "light-pillar",
    name: "LightPillar",
    source: "reactbits",
    category: "background",
    mood: ["dramatic", "elegant"],
    eventTypes: ["elopement", "wedding", "anniversary"],
    intensity: "medium",
    description: "Vertical pillars of light rising upward",
  },
  {
    id: "light-rays",
    name: "LightRays",
    source: "reactbits",
    category: "background",
    mood: ["romantic", "dramatic"],
    eventTypes: ["wedding", "elopement"],
    intensity: "medium",
    description: "Volumetric god rays filtering through",
  },
  {
    id: "lightning",
    name: "Lightning",
    source: "reactbits",
    category: "background",
    mood: ["dramatic"],
    eventTypes: ["celebration", "elopement"],
    intensity: "dramatic",
    description: "Electric lightning strikes and arcs",
  },
  {
    id: "line-waves",
    name: "LineWaves",
    source: "reactbits",
    category: "background",
    mood: ["elegant", "modern"],
    eventTypes: ["elopement", "wedding", "anniversary"],
    intensity: "subtle",
    description: "Flowing wave lines in gentle motion",
  },
  {
    id: "liquid-chrome",
    name: "LiquidChrome",
    source: "reactbits",
    category: "background",
    mood: ["modern", "dramatic"],
    eventTypes: ["engagement", "celebration"],
    intensity: "dramatic",
    description: "Liquid metal chrome surface reflections",
  },
  {
    id: "liquid-ether",
    name: "LiquidEther",
    source: "reactbits",
    category: "background",
    mood: ["romantic", "whimsical"],
    eventTypes: ["anniversary", "wedding", "vow-renewal"],
    intensity: "medium",
    description: "Slow-moving ethereal liquid color blending",
  },
  {
    id: "orb",
    name: "Orb",
    source: "reactbits",
    category: "background",
    mood: ["whimsical", "romantic"],
    eventTypes: ["wedding", "engagement"],
    intensity: "medium",
    description: "Glowing orb of light with soft halo",
  },
  {
    id: "particles",
    name: "Particles",
    source: "reactbits",
    category: "background",
    mood: ["playful", "whimsical"],
    eventTypes: ["engagement", "celebration", "wedding"],
    intensity: "medium",
    description: "Floating particle field with gentle drift",
  },
  {
    id: "pixel-blast",
    name: "PixelBlast",
    source: "reactbits",
    category: "background",
    mood: ["playful", "dramatic"],
    eventTypes: ["celebration", "engagement"],
    intensity: "dramatic",
    description: "Exploding pixel burst animation",
  },
  {
    id: "pixel-snow",
    name: "PixelSnow",
    source: "reactbits",
    category: "background",
    mood: ["whimsical", "playful"],
    eventTypes: ["wedding", "celebration"],
    intensity: "subtle",
    description: "Gentle falling pixel snowflakes",
  },
  {
    id: "plasma",
    name: "Plasma",
    source: "reactbits",
    category: "background",
    mood: ["dramatic", "modern"],
    eventTypes: ["celebration", "engagement"],
    intensity: "dramatic",
    description: "Pulsing plasma energy field",
  },
  {
    id: "plasma-wave",
    name: "PlasmaWave",
    source: "reactbits",
    category: "background",
    mood: ["dramatic", "modern"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Undulating plasma wave ripples",
  },
  {
    id: "prism",
    name: "Prism",
    source: "reactbits",
    category: "background",
    mood: ["elegant", "modern"],
    eventTypes: ["wedding", "engagement"],
    intensity: "medium",
    description: "Light refraction through prismatic surface",
  },
  {
    id: "prismatic-burst",
    name: "PrismaticBurst",
    source: "reactbits",
    category: "background",
    mood: ["playful", "dramatic"],
    eventTypes: ["celebration", "engagement"],
    intensity: "dramatic",
    description: "Rainbow prismatic light explosion",
  },
  {
    id: "radar",
    name: "Radar",
    source: "reactbits",
    category: "background",
    mood: ["modern"],
    eventTypes: ["celebration"],
    intensity: "subtle",
    description: "Rotating radar sweep with blips",
  },
  {
    id: "ripple-grid",
    name: "RippleGrid",
    source: "reactbits",
    category: "background",
    mood: ["modern", "elegant"],
    eventTypes: "*",
    intensity: "subtle",
    description: "Grid with ripple wave propagation",
  },
  {
    id: "shape-grid",
    name: "ShapeGrid",
    source: "reactbits",
    category: "background",
    mood: ["modern", "playful"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Grid of animated geometric shapes",
  },
  {
    id: "silk",
    name: "Silk",
    source: "reactbits",
    category: "background",
    mood: ["romantic", "elegant"],
    eventTypes: ["wedding", "vow-renewal", "anniversary"],
    intensity: "subtle",
    description: "Flowing silk fabric in gentle motion",
  },
  {
    id: "soft-aurora",
    name: "SoftAurora",
    source: "reactbits",
    category: "background",
    mood: ["romantic", "whimsical"],
    eventTypes: ["wedding", "vow-renewal"],
    intensity: "subtle",
    description: "Soft pastel aurora light wash",
  },
  {
    id: "threads",
    name: "Threads",
    source: "reactbits",
    category: "background",
    mood: ["elegant", "romantic"],
    eventTypes: ["wedding", "anniversary"],
    intensity: "subtle",
    description: "Delicate interwoven thread animation",
  },
  {
    id: "waves",
    name: "Waves",
    source: "reactbits",
    category: "background",
    mood: ["elegant", "romantic"],
    eventTypes: ["wedding", "elopement", "anniversary"],
    intensity: "subtle",
    description: "Smooth ocean-like wave undulation",
  },

  // ═══════════════════════════════════════════
  // TEXT ANIMATIONS (23)
  // ═══════════════════════════════════════════
  {
    id: "ascii-text",
    name: "ASCIIText",
    source: "reactbits",
    category: "text",
    mood: ["modern", "dramatic"],
    eventTypes: ["celebration", "engagement"],
    intensity: "dramatic",
    description: "Text rendered as animated ASCII art",
  },
  {
    id: "blur-text",
    name: "BlurText",
    source: "reactbits",
    category: "text",
    mood: ["romantic", "elegant"],
    eventTypes: ["wedding", "elopement", "vow-renewal"],
    intensity: "subtle",
    description: "Text fades in from blur on scroll",
  },
  {
    id: "circular-text",
    name: "CircularText",
    source: "reactbits",
    category: "text",
    mood: ["playful", "whimsical"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Text arranged in a rotating circle",
  },
  {
    id: "count-up",
    name: "CountUp",
    source: "reactbits",
    category: "text",
    mood: ["modern", "elegant"],
    eventTypes: ["anniversary", "celebration"],
    intensity: "subtle",
    description: "Numbers count up with easing animation",
  },
  {
    id: "curved-loop",
    name: "CurvedLoop",
    source: "reactbits",
    category: "text",
    mood: ["playful", "whimsical"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Text follows a curved looping path",
  },
  {
    id: "decrypted-text",
    name: "DecryptedText",
    source: "reactbits",
    category: "text",
    mood: ["modern", "dramatic"],
    eventTypes: ["elopement", "engagement"],
    intensity: "medium",
    description: "Text scrambles then decodes into readable form",
  },
  {
    id: "falling-text",
    name: "FallingText",
    source: "reactbits",
    category: "text",
    mood: ["playful", "dramatic"],
    eventTypes: ["engagement", "celebration"],
    intensity: "dramatic",
    description: "Letters fall from above with physics",
  },
  {
    id: "fuzzy-text",
    name: "FuzzyText",
    source: "reactbits",
    category: "text",
    mood: ["whimsical", "playful"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Text with fuzzy static distortion effect",
  },
  {
    id: "glitch-text",
    name: "GlitchText",
    source: "reactbits",
    category: "text",
    mood: ["modern", "dramatic"],
    eventTypes: ["celebration", "engagement"],
    intensity: "dramatic",
    description: "Text with digital glitch distortion",
  },
  {
    id: "gradient-text",
    name: "GradientText",
    source: "reactbits",
    category: "text",
    mood: ["elegant", "romantic"],
    eventTypes: ["wedding", "anniversary", "vow-renewal"],
    intensity: "subtle",
    description: "Animated gradient flowing through text",
  },
  {
    id: "rotating-text",
    name: "RotatingText",
    source: "reactbits",
    category: "text",
    mood: ["playful", "modern"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Words cycle through with rotation animation",
  },
  {
    id: "scrambled-text",
    name: "ScrambledText",
    source: "reactbits",
    category: "text",
    mood: ["modern", "dramatic"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Letters randomly scramble before resolving",
  },
  {
    id: "scroll-float",
    name: "ScrollFloat",
    source: "reactbits",
    category: "text",
    mood: ["elegant", "romantic"],
    eventTypes: ["wedding", "anniversary", "elopement"],
    intensity: "subtle",
    description: "Text gently floats into view on scroll",
  },
  {
    id: "scroll-reveal",
    name: "ScrollReveal",
    source: "reactbits",
    category: "text",
    mood: ["elegant", "romantic"],
    eventTypes: ["wedding", "vow-renewal", "anniversary"],
    intensity: "subtle",
    description: "Text progressively reveals on scroll position",
  },
  {
    id: "scroll-velocity",
    name: "ScrollVelocity",
    source: "reactbits",
    category: "text",
    mood: ["modern", "dramatic"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Text speed responds to scroll velocity",
  },
  {
    id: "shiny-text",
    name: "ShinyText",
    source: "reactbits",
    category: "text",
    mood: ["elegant", "playful"],
    eventTypes: ["anniversary", "engagement", "celebration"],
    intensity: "subtle",
    description: "Shimmer highlight sweeps across text",
  },
  {
    id: "shuffle",
    name: "Shuffle",
    source: "reactbits",
    category: "text",
    mood: ["playful", "modern"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Letters shuffle positions then settle",
  },
  {
    id: "split-text",
    name: "SplitText",
    source: "reactbits",
    category: "text",
    mood: ["elegant", "modern"],
    eventTypes: ["wedding", "anniversary"],
    intensity: "subtle",
    description: "Characters animate in one by one",
  },
  {
    id: "text-cursor",
    name: "TextCursor",
    source: "reactbits",
    category: "text",
    mood: ["modern"],
    eventTypes: ["engagement", "celebration"],
    intensity: "subtle",
    description: "Typewriter cursor blink on text",
  },
  {
    id: "text-pressure",
    name: "TextPressure",
    source: "reactbits",
    category: "text",
    mood: ["modern", "dramatic"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Text weight responds to cursor proximity",
  },
  {
    id: "text-type",
    name: "TextType",
    source: "reactbits",
    category: "text",
    mood: ["modern", "elegant"],
    eventTypes: "*",
    intensity: "subtle",
    description: "Typewriter effect that types out text",
  },
  {
    id: "true-focus",
    name: "TrueFocus",
    source: "reactbits",
    category: "text",
    mood: ["elegant", "dramatic"],
    eventTypes: ["wedding", "elopement"],
    intensity: "medium",
    description: "Only focused word is sharp, rest blurred",
  },
  {
    id: "variable-proximity",
    name: "VariableProximity",
    source: "reactbits",
    category: "text",
    mood: ["modern", "playful"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Text weight shifts based on cursor distance",
  },

  // ═══════════════════════════════════════════
  // TRANSITIONS (6 — from Animations)
  // ═══════════════════════════════════════════
  {
    id: "animated-content",
    name: "AnimatedContent",
    source: "reactbits",
    category: "transition",
    mood: ["modern", "elegant"],
    eventTypes: "*",
    intensity: "subtle",
    description: "Content animates in with spring physics",
  },
  {
    id: "fade-content",
    name: "FadeContent",
    source: "reactbits",
    category: "transition",
    mood: ["elegant", "romantic"],
    eventTypes: ["wedding", "anniversary", "vow-renewal"],
    intensity: "subtle",
    description: "Smooth fade-in on scroll into view",
  },
  {
    id: "gradual-blur",
    name: "GradualBlur",
    source: "reactbits",
    category: "transition",
    mood: ["elegant", "romantic"],
    eventTypes: ["anniversary", "elopement", "vow-renewal"],
    intensity: "subtle",
    description: "Content unblurs gradually on entrance",
  },
  {
    id: "pixel-transition",
    name: "PixelTransition",
    source: "reactbits",
    category: "transition",
    mood: ["modern", "playful"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Pixelated dissolve transition between states",
  },
  {
    id: "shape-blur",
    name: "ShapeBlur",
    source: "reactbits",
    category: "transition",
    mood: ["dramatic", "whimsical"],
    eventTypes: ["elopement"],
    intensity: "medium",
    description: "Blurred shape morph entrance animation",
  },
  {
    id: "sticker-peel",
    name: "StickerPeel",
    source: "reactbits",
    category: "transition",
    mood: ["playful", "whimsical"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Content peels away like a sticker",
  },

  // ═══════════════════════════════════════════
  // CURSOR EFFECTS (6 — from Animations)
  // ═══════════════════════════════════════════
  {
    id: "blob-cursor",
    name: "BlobCursor",
    source: "reactbits",
    category: "cursor",
    mood: ["playful", "whimsical"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Morphing blob follows cursor movement",
  },
  {
    id: "crosshair",
    name: "Crosshair",
    source: "reactbits",
    category: "cursor",
    mood: ["modern"],
    eventTypes: ["celebration", "engagement"],
    intensity: "subtle",
    description: "Custom crosshair cursor replacement",
  },
  {
    id: "ghost-cursor",
    name: "GhostCursor",
    source: "reactbits",
    category: "cursor",
    mood: ["whimsical", "playful"],
    eventTypes: ["celebration"],
    intensity: "medium",
    description: "Trailing ghost images follow cursor",
  },
  {
    id: "pixel-trail",
    name: "PixelTrail",
    source: "reactbits",
    category: "cursor",
    mood: ["playful", "modern"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Pixelated trail follows cursor movement",
  },
  {
    id: "splash-cursor",
    name: "SplashCursor",
    source: "reactbits",
    category: "cursor",
    mood: ["playful", "whimsical"],
    eventTypes: ["celebration", "engagement"],
    intensity: "dramatic",
    description: "Fluid splash effect at cursor position",
  },
  {
    id: "target-cursor",
    name: "TargetCursor",
    source: "reactbits",
    category: "cursor",
    mood: ["modern"],
    eventTypes: ["celebration"],
    intensity: "subtle",
    description: "Animated target reticle follows cursor",
  },

  // ═══════════════════════════════════════════
  // DECORATIONS (12 — from Animations)
  // ═══════════════════════════════════════════
  {
    id: "antigravity",
    name: "Antigravity",
    source: "reactbits",
    category: "decoration",
    mood: ["whimsical", "playful"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Elements float upward defying gravity",
  },
  {
    id: "click-spark",
    name: "ClickSpark",
    source: "reactbits",
    category: "decoration",
    mood: ["playful", "whimsical"],
    eventTypes: ["wedding", "engagement", "celebration"],
    intensity: "subtle",
    description: "Sparkle burst on every click",
  },
  {
    id: "cubes",
    name: "Cubes",
    source: "reactbits",
    category: "decoration",
    mood: ["modern", "dramatic"],
    eventTypes: ["celebration", "engagement"],
    intensity: "dramatic",
    description: "3D cubes floating in space",
  },
  {
    id: "electric-border",
    name: "ElectricBorder",
    source: "reactbits",
    category: "decoration",
    mood: ["dramatic", "modern"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Electric arcs along element borders",
  },
  {
    id: "glare-hover",
    name: "GlareHover",
    source: "reactbits",
    category: "decoration",
    mood: ["elegant", "modern"],
    eventTypes: "*",
    intensity: "subtle",
    description: "Light glare follows hover position",
  },
  {
    id: "laser-flow",
    name: "LaserFlow",
    source: "reactbits",
    category: "decoration",
    mood: ["modern", "dramatic"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Flowing laser beam animation along edges",
  },
  {
    id: "magic-rings",
    name: "MagicRings",
    source: "reactbits",
    category: "decoration",
    mood: ["whimsical", "romantic"],
    eventTypes: ["wedding", "engagement"],
    intensity: "medium",
    description: "Concentric magical ring animations",
  },
  {
    id: "magnet",
    name: "Magnet",
    source: "reactbits",
    category: "decoration",
    mood: ["playful", "modern"],
    eventTypes: ["engagement", "celebration"],
    intensity: "subtle",
    description: "Elements magnetically attract to cursor",
  },
  {
    id: "magnet-lines",
    name: "MagnetLines",
    source: "reactbits",
    category: "decoration",
    mood: ["modern", "elegant"],
    eventTypes: "*",
    intensity: "subtle",
    description: "Lines bend toward cursor like a magnet",
  },
  {
    id: "meta-balls",
    name: "MetaBalls",
    source: "reactbits",
    category: "decoration",
    mood: ["playful", "whimsical"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Merging organic blob shapes",
  },
  {
    id: "ribbons",
    name: "Ribbons",
    source: "reactbits",
    category: "decoration",
    mood: ["romantic", "elegant"],
    eventTypes: ["wedding", "celebration", "engagement"],
    intensity: "medium",
    description: "Flowing ribbon streamers animation",
  },
  {
    id: "star-border",
    name: "StarBorder",
    source: "reactbits",
    category: "decoration",
    mood: ["whimsical", "playful"],
    eventTypes: ["wedding", "celebration", "engagement"],
    intensity: "subtle",
    description: "Twinkling star particles along borders",
  },

  // ═══════════════════════════════════════════
  // CARD / UI COMPONENTS (22 — from Components)
  // ═══════════════════════════════════════════
  {
    id: "animated-list",
    name: "AnimatedList",
    source: "reactbits",
    category: "card",
    mood: ["modern", "elegant"],
    eventTypes: "*",
    intensity: "subtle",
    description: "List items animate in sequentially",
  },
  {
    id: "border-glow",
    name: "BorderGlow",
    source: "reactbits",
    category: "card",
    mood: ["modern", "dramatic"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Glowing animated border effect on cards",
  },
  {
    id: "bounce-cards",
    name: "BounceCards",
    source: "reactbits",
    category: "card",
    mood: ["playful"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Cards bounce and stack with physics",
  },
  {
    id: "card-swap",
    name: "CardSwap",
    source: "reactbits",
    category: "card",
    mood: ["playful", "modern"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Cards swap positions with animation",
  },
  {
    id: "carousel",
    name: "Carousel",
    source: "reactbits",
    category: "card",
    mood: ["modern", "elegant"],
    eventTypes: "*",
    intensity: "subtle",
    description: "Smooth 3D carousel gallery",
  },
  {
    id: "chroma-grid",
    name: "ChromaGrid",
    source: "reactbits",
    category: "card",
    mood: ["modern", "playful"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Color-shifting grid of image tiles",
  },
  {
    id: "circular-gallery",
    name: "CircularGallery",
    source: "reactbits",
    category: "card",
    mood: ["elegant", "modern"],
    eventTypes: ["anniversary", "wedding"],
    intensity: "medium",
    description: "Gallery arranged in circular layout",
  },
  {
    id: "decay-card",
    name: "DecayCard",
    source: "reactbits",
    category: "card",
    mood: ["dramatic", "modern"],
    eventTypes: ["elopement"],
    intensity: "medium",
    description: "Card with organic decay/erosion effect",
  },
  {
    id: "dome-gallery",
    name: "DomeGallery",
    source: "reactbits",
    category: "card",
    mood: ["dramatic", "elegant"],
    eventTypes: ["anniversary", "wedding"],
    intensity: "dramatic",
    description: "3D dome-shaped gallery display",
  },
  {
    id: "fluid-glass",
    name: "FluidGlass",
    source: "reactbits",
    category: "card",
    mood: ["modern", "elegant"],
    eventTypes: ["wedding", "engagement"],
    intensity: "medium",
    description: "Glass card with fluid distortion effect",
  },
  {
    id: "flying-posters",
    name: "FlyingPosters",
    source: "reactbits",
    category: "card",
    mood: ["playful", "dramatic"],
    eventTypes: ["celebration", "engagement"],
    intensity: "dramatic",
    description: "Poster cards flying through 3D space",
  },
  {
    id: "folder",
    name: "Folder",
    source: "reactbits",
    category: "card",
    mood: ["playful", "modern"],
    eventTypes: ["celebration"],
    intensity: "subtle",
    description: "Interactive folder that opens to reveal content",
  },
  {
    id: "glass-surface",
    name: "GlassSurface",
    source: "reactbits",
    category: "card",
    mood: ["elegant", "modern"],
    eventTypes: ["wedding", "vow-renewal", "anniversary"],
    intensity: "subtle",
    description: "Frosted glass surface with refraction",
  },
  {
    id: "magic-bento",
    name: "MagicBento",
    source: "reactbits",
    category: "card",
    mood: ["modern", "playful"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Animated bento grid with hover effects",
  },
  {
    id: "masonry",
    name: "Masonry",
    source: "reactbits",
    category: "card",
    mood: ["modern", "elegant"],
    eventTypes: "*",
    intensity: "subtle",
    description: "Animated masonry photo grid layout",
  },
  {
    id: "pixel-card",
    name: "PixelCard",
    source: "reactbits",
    category: "card",
    mood: ["modern", "playful"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Card with pixel dissolve hover effect",
  },
  {
    id: "profile-card",
    name: "ProfileCard",
    source: "reactbits",
    category: "card",
    mood: ["elegant", "modern"],
    eventTypes: "*",
    intensity: "subtle",
    description: "Animated profile card with hover reveal",
  },
  {
    id: "reflective-card",
    name: "ReflectiveCard",
    source: "reactbits",
    category: "card",
    mood: ["elegant", "dramatic"],
    eventTypes: ["anniversary", "wedding"],
    intensity: "medium",
    description: "Card with holographic reflective surface",
  },
  {
    id: "scroll-stack",
    name: "ScrollStack",
    source: "reactbits",
    category: "card",
    mood: ["modern", "elegant"],
    eventTypes: "*",
    intensity: "medium",
    description: "Cards stack and unstack on scroll",
  },
  {
    id: "spotlight-card",
    name: "SpotlightCard",
    source: "reactbits",
    category: "card",
    mood: ["elegant", "dramatic"],
    eventTypes: ["wedding", "anniversary", "vow-renewal"],
    intensity: "subtle",
    description: "Spotlight follows cursor over card surface",
  },
  {
    id: "stack",
    name: "Stack",
    source: "reactbits",
    category: "card",
    mood: ["modern"],
    eventTypes: "*",
    intensity: "subtle",
    description: "Stacked cards that fan out on interaction",
  },
  {
    id: "tilted-card",
    name: "TiltedCard",
    source: "reactbits",
    category: "card",
    mood: ["modern", "playful"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "3D tilt effect following cursor position",
  },

  // ═══════════════════════════════════════════
  // NAV STYLES (6, custom) + DECORATIONS (kept)
  // ═══════════════════════════════════════════
  {
    id: "glass-dropdown",
    name: "GlassDropdown",
    source: "reactbits",
    category: "nav-style",
    mood: ["modern", "elegant"],
    eventTypes: "*",
    intensity: "medium",
    description: "Frosted glass dropdown with staggered reveals",
  },
  {
    id: "glass-slide",
    name: "GlassSlide",
    source: "reactbits",
    category: "nav-style",
    mood: ["modern", "elegant"],
    eventTypes: "*",
    intensity: "subtle",
    description: "Glass bar with spring-animated pill indicator",
  },
  {
    id: "glass-morph",
    name: "GlassMorph",
    source: "reactbits",
    category: "nav-style",
    mood: ["elegant", "dramatic"],
    eventTypes: ["wedding", "anniversary", "vow-renewal"],
    intensity: "medium",
    description: "Centered glass pill with chromatic shimmer border",
  },
  {
    id: "glow-nav",
    name: "GlowNav",
    source: "reactbits",
    category: "nav-style",
    mood: ["dramatic", "modern"],
    eventTypes: ["elopement", "celebration", "engagement"],
    intensity: "medium",
    description: "Dark nav with luminous glow orb on active item",
  },
  {
    id: "magnetic-hover",
    name: "MagneticHover",
    source: "reactbits",
    category: "nav-style",
    mood: ["modern", "playful"],
    eventTypes: "*",
    intensity: "subtle",
    description: "Items spring-scale on hover with magnetic feel",
  },
  {
    id: "minimal-fade",
    name: "MinimalFade",
    source: "reactbits",
    category: "nav-style",
    mood: ["elegant", "romantic"],
    eventTypes: ["wedding", "vow-renewal", "anniversary"],
    intensity: "subtle",
    description: "Ultra-clean nav with staggered fade-in",
  },
  {
    id: "counter",
    name: "Counter",
    source: "reactbits",
    category: "decoration",
    mood: ["modern", "elegant"],
    eventTypes: ["anniversary", "celebration"],
    intensity: "subtle",
    description: "Animated number counter component",
  },
  {
    id: "elastic-slider",
    name: "ElasticSlider",
    source: "reactbits",
    category: "decoration",
    mood: ["playful", "modern"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Slider with elastic snap-back physics",
  },
  {
    id: "lanyard",
    name: "Lanyard",
    source: "reactbits",
    category: "decoration",
    mood: ["playful", "whimsical"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Dangling lanyard badge with physics",
  },
  {
    id: "stepper",
    name: "Stepper",
    source: "reactbits",
    category: "decoration",
    mood: ["modern"],
    eventTypes: "*",
    intensity: "subtle",
    description: "Animated step-by-step progress indicator",
  },
  {
    id: "model-viewer",
    name: "ModelViewer",
    source: "reactbits",
    category: "decoration",
    mood: ["modern", "dramatic"],
    eventTypes: ["celebration"],
    intensity: "dramatic",
    description: "Interactive 3D model viewer component",
  },
];

export function getEffectsByCategory(category: EffectCategory): EffectEntry[] {
  return EFFECT_REGISTRY.filter((e) => e.category === category);
}

export function getRecommended(
  category: EffectCategory,
  eventType: EventType,
): EffectEntry[] {
  return EFFECT_REGISTRY.filter(
    (e) =>
      e.category === category &&
      (e.eventTypes === "*" || e.eventTypes.includes(eventType)),
  );
}

export function getEffectById(id: string): EffectEntry | undefined {
  return EFFECT_REGISTRY.find((e) => e.id === id);
}
