import type { EffectEntry, EffectCategory, EventType } from "./types";

export const EFFECT_REGISTRY: EffectEntry[] = [
  // ═══════════════════════════════════════════
  // BACKGROUNDS (42)
  // ═══════════════════════════════════════════
  {
    id: "aurora",
    name: "Aurora",
    source: "reactbits",
    category: "background",
    mood: ["dramatic", "whimsical"],
    eventTypes: ["wedding", "anniversary", "elopement"],
    intensity: "medium",
    description: "Flowing aurora borealis light ribbons",
  },
  {
    id: "balatro",
    name: "Balatro",
    source: "reactbits",
    category: "background",
    mood: ["playful", "dramatic"],
    eventTypes: ["celebration", "engagement"],
    intensity: "dramatic",
    description: "Psychedelic swirling color distortion",
  },
  {
    id: "ballpit",
    name: "Ballpit",
    source: "reactbits",
    category: "background",
    mood: ["playful"],
    eventTypes: ["engagement", "celebration"],
    intensity: "dramatic",
    description: "Interactive 3D ball physics simulation",
  },
  {
    id: "beams",
    name: "Beams",
    source: "reactbits",
    category: "background",
    mood: ["elegant", "dramatic"],
    eventTypes: ["wedding", "elopement", "celebration"],
    intensity: "medium",
    description: "Converging light beams from above",
  },
  {
    id: "color-bends",
    name: "ColorBends",
    source: "reactbits",
    category: "background",
    mood: ["modern", "playful"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Bending color gradients that shift on scroll",
  },
  {
    id: "dark-veil",
    name: "DarkVeil",
    source: "reactbits",
    category: "background",
    mood: ["dramatic", "elegant"],
    eventTypes: ["elopement", "anniversary"],
    intensity: "subtle",
    description: "Dark atmospheric fog overlay",
  },
  {
    id: "dither",
    name: "Dither",
    source: "reactbits",
    category: "background",
    mood: ["modern"],
    eventTypes: ["engagement", "elopement"],
    intensity: "subtle",
    description: "Retro dithering pattern with gradient",
  },
  {
    id: "dot-field",
    name: "DotField",
    source: "reactbits",
    category: "background",
    mood: ["modern", "elegant"],
    eventTypes: "*",
    intensity: "subtle",
    description: "Field of animated dots reacting to cursor",
  },
  {
    id: "evil-eye",
    name: "EvilEye",
    source: "reactbits",
    category: "background",
    mood: ["dramatic", "whimsical"],
    eventTypes: ["celebration"],
    intensity: "dramatic",
    description: "Animated eye that follows cursor movement",
  },
  {
    id: "faulty-terminal",
    name: "FaultyTerminal",
    source: "reactbits",
    category: "background",
    mood: ["modern", "dramatic"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Glitchy terminal screen with scan lines",
  },
  {
    id: "floating-lines",
    name: "FloatingLines",
    source: "reactbits",
    category: "background",
    mood: ["elegant", "romantic"],
    eventTypes: ["wedding", "vow-renewal", "anniversary"],
    intensity: "subtle",
    description: "Gently drifting minimal line patterns",
  },
  {
    id: "galaxy",
    name: "Galaxy",
    source: "reactbits",
    category: "background",
    mood: ["dramatic", "whimsical"],
    eventTypes: ["elopement", "celebration"],
    intensity: "dramatic",
    description: "Deep space galaxy with swirling stars",
  },
  {
    id: "gradient-blinds",
    name: "GradientBlinds",
    source: "reactbits",
    category: "background",
    mood: ["modern", "elegant"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Animated gradient blinds transition effect",
  },
  {
    id: "grainient",
    name: "Grainient",
    source: "reactbits",
    category: "background",
    mood: ["elegant", "romantic"],
    eventTypes: ["anniversary", "wedding", "vow-renewal"],
    intensity: "subtle",
    description: "Warm grainy gradient with film texture",
  },
  {
    id: "grid-distortion",
    name: "GridDistortion",
    source: "reactbits",
    category: "background",
    mood: ["modern", "dramatic"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Grid that warps and distorts on interaction",
  },
  {
    id: "grid-motion",
    name: "GridMotion",
    source: "reactbits",
    category: "background",
    mood: ["modern", "playful"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Animated grid cells with shifting images",
  },
  {
    id: "grid-scan",
    name: "GridScan",
    source: "reactbits",
    category: "background",
    mood: ["modern", "dramatic"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Scanning beam sweeps over a grid pattern",
  },
  {
    id: "hyperspeed",
    name: "Hyperspeed",
    source: "reactbits",
    category: "background",
    mood: ["dramatic", "modern"],
    eventTypes: ["celebration", "engagement"],
    intensity: "dramatic",
    description: "Star-field warp speed tunnel effect",
  },
  {
    id: "iridescence",
    name: "Iridescence",
    source: "reactbits",
    category: "background",
    mood: ["romantic", "whimsical"],
    eventTypes: ["wedding", "engagement", "vow-renewal"],
    intensity: "medium",
    description: "Shimmering iridescent color surface",
  },
  {
    id: "letter-glitch",
    name: "LetterGlitch",
    source: "reactbits",
    category: "background",
    mood: ["modern", "dramatic"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Glitching letter matrix background",
  },
  {
    id: "light-pillar",
    name: "LightPillar",
    source: "reactbits",
    category: "background",
    mood: ["dramatic", "elegant"],
    eventTypes: ["elopement", "wedding", "anniversary"],
    intensity: "medium",
    description: "Vertical pillars of light rising upward",
  },
  {
    id: "light-rays",
    name: "LightRays",
    source: "reactbits",
    category: "background",
    mood: ["romantic", "dramatic"],
    eventTypes: ["wedding", "elopement"],
    intensity: "medium",
    description: "Volumetric god rays filtering through",
  },
  {
    id: "lightning",
    name: "Lightning",
    source: "reactbits",
    category: "background",
    mood: ["dramatic"],
    eventTypes: ["celebration", "elopement"],
    intensity: "dramatic",
    description: "Electric lightning strikes and arcs",
  },
  {
    id: "line-waves",
    name: "LineWaves",
    source: "reactbits",
    category: "background",
    mood: ["elegant", "modern"],
    eventTypes: ["elopement", "wedding", "anniversary"],
    intensity: "subtle",
    description: "Flowing wave lines in gentle motion",
  },
  {
    id: "liquid-chrome",
    name: "LiquidChrome",
    source: "reactbits",
    category: "background",
    mood: ["modern", "dramatic"],
    eventTypes: ["engagement", "celebration"],
    intensity: "dramatic",
    description: "Liquid metal chrome surface reflections",
  },
  {
    id: "liquid-ether",
    name: "LiquidEther",
    source: "reactbits",
    category: "background",
    mood: ["romantic", "whimsical"],
    eventTypes: ["anniversary", "wedding", "vow-renewal"],
    intensity: "medium",
    description: "Slow-moving ethereal liquid color blending",
  },
  {
    id: "orb",
    name: "Orb",
    source: "reactbits",
    category: "background",
    mood: ["whimsical", "romantic"],
    eventTypes: ["wedding", "engagement"],
    intensity: "medium",
    description: "Glowing orb of light with soft halo",
  },
  {
    id: "particles",
    name: "Particles",
    source: "reactbits",
    category: "background",
    mood: ["playful", "whimsical"],
    eventTypes: ["engagement", "celebration", "wedding"],
    intensity: "medium",
    description: "Floating particle field with gentle drift",
  },
  {
    id: "pixel-blast",
    name: "PixelBlast",
    source: "reactbits",
    category: "background",
    mood: ["playful", "dramatic"],
    eventTypes: ["celebration", "engagement"],
    intensity: "dramatic",
    description: "Exploding pixel burst animation",
  },
  {
    id: "pixel-snow",
    name: "PixelSnow",
    source: "reactbits",
    category: "background",
    mood: ["whimsical", "playful"],
    eventTypes: ["wedding", "celebration"],
    intensity: "subtle",
    description: "Gentle falling pixel snowflakes",
  },
  {
    id: "plasma",
    name: "Plasma",
    source: "reactbits",
    category: "background",
    mood: ["dramatic", "modern"],
    eventTypes: ["celebration", "engagement"],
    intensity: "dramatic",
    description: "Pulsing plasma energy field",
  },
  {
    id: "plasma-wave",
    name: "PlasmaWave",
    source: "reactbits",
    category: "background",
    mood: ["dramatic", "modern"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Undulating plasma wave ripples",
  },
  {
    id: "prism",
    name: "Prism",
    source: "reactbits",
    category: "background",
    mood: ["elegant", "modern"],
    eventTypes: ["wedding", "engagement"],
    intensity: "medium",
    description: "Light refraction through prismatic surface",
  },
  {
    id: "prismatic-burst",
    name: "PrismaticBurst",
    source: "reactbits",
    category: "background",
    mood: ["playful", "dramatic"],
    eventTypes: ["celebration", "engagement"],
    intensity: "dramatic",
    description: "Rainbow prismatic light explosion",
  },
  {
    id: "radar",
    name: "Radar",
    source: "reactbits",
    category: "background",
    mood: ["modern"],
    eventTypes: ["celebration"],
    intensity: "subtle",
    description: "Rotating radar sweep with blips",
  },
  {
    id: "ripple-grid",
    name: "RippleGrid",
    source: "reactbits",
    category: "background",
    mood: ["modern", "elegant"],
    eventTypes: "*",
    intensity: "subtle",
    description: "Grid with ripple wave propagation",
  },
  {
    id: "shape-grid",
    name: "ShapeGrid",
    source: "reactbits",
    category: "background",
    mood: ["modern", "playful"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Grid of animated geometric shapes",
  },
  {
    id: "silk",
    name: "Silk",
    source: "reactbits",
    category: "background",
    mood: ["romantic", "elegant"],
    eventTypes: ["wedding", "vow-renewal", "anniversary"],
    intensity: "subtle",
    description: "Flowing silk fabric in gentle motion",
  },
  {
    id: "soft-aurora",
    name: "SoftAurora",
    source: "reactbits",
    category: "background",
    mood: ["romantic", "whimsical"],
    eventTypes: ["wedding", "vow-renewal"],
    intensity: "subtle",
    description: "Soft pastel aurora light wash",
  },
  {
    id: "threads",
    name: "Threads",
    source: "reactbits",
    category: "background",
    mood: ["elegant", "romantic"],
    eventTypes: ["wedding", "anniversary"],
    intensity: "subtle",
    description: "Delicate interwoven thread animation",
  },
  {
    id: "waves",
    name: "Waves",
    source: "reactbits",
    category: "background",
    mood: ["elegant", "romantic"],
    eventTypes: ["wedding", "elopement", "anniversary"],
    intensity: "subtle",
    description: "Smooth ocean-like wave undulation",
  },

  // ═══════════════════════════════════════════
  // TEXT STYLES (6)
  // ═══════════════════════════════════════════
  {
    id: "fuzzy-text",
    name: "FuzzyText",
    source: "reactbits",
    category: "text",
    mood: ["whimsical", "playful"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Text with fuzzy static distortion effect",
  },
  {
    id: "glitch-text",
    name: "GlitchText",
    source: "reactbits",
    category: "text",
    mood: ["modern", "dramatic"],
    eventTypes: ["celebration", "engagement"],
    intensity: "dramatic",
    description: "Text with digital glitch distortion",
  },
  {
    id: "gradient-text",
    name: "GradientText",
    source: "reactbits",
    category: "text",
    mood: ["elegant", "romantic"],
    eventTypes: ["wedding", "anniversary", "vow-renewal"],
    intensity: "subtle",
    description: "Animated gradient flowing through text",
  },
  {
    id: "shiny-text",
    name: "ShinyText",
    source: "reactbits",
    category: "text",
    mood: ["elegant", "playful"],
    eventTypes: ["anniversary", "engagement", "celebration"],
    intensity: "subtle",
    description: "Shimmer highlight sweeps across text",
  },
  {
    id: "text-pressure",
    name: "TextPressure",
    source: "reactbits",
    category: "text",
    mood: ["modern", "dramatic"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Text weight responds to cursor proximity",
  },
  // ═══════════════════════════════════════════
  // CURSOR EFFECTS (3 — from Animations)
  // ═══════════════════════════════════════════
  {
    id: "crosshair",
    name: "Crosshair",
    source: "reactbits",
    category: "cursor",
    mood: ["modern"],
    eventTypes: ["celebration", "engagement"],
    intensity: "subtle",
    description: "Custom crosshair cursor replacement",
  },
  {
    id: "pixel-trail",
    name: "PixelTrail",
    source: "reactbits",
    category: "cursor",
    mood: ["playful", "modern"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Pixelated trail follows cursor movement",
  },
  {
    id: "target-cursor",
    name: "TargetCursor",
    source: "reactbits",
    category: "cursor",
    mood: ["modern"],
    eventTypes: ["celebration"],
    intensity: "subtle",
    description: "Animated target reticle follows cursor",
  },

  // ═══════════════════════════════════════════
  // DECORATIONS (12 — from Animations)
  // ═══════════════════════════════════════════
  {
    id: "antigravity",
    name: "Antigravity",
    source: "reactbits",
    category: "decoration",
    mood: ["whimsical", "playful"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Elements float upward defying gravity",
  },
  {
    id: "electric-border",
    name: "ElectricBorder",
    source: "reactbits",
    category: "decoration",
    mood: ["dramatic", "modern"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Electric arcs along element borders",
  },
  {
    id: "laser-flow",
    name: "LaserFlow",
    source: "reactbits",
    category: "decoration",
    mood: ["modern", "dramatic"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Flowing laser beam animation along edges",
  },
  {
    id: "magic-rings",
    name: "MagicRings",
    source: "reactbits",
    category: "decoration",
    mood: ["whimsical", "romantic"],
    eventTypes: ["wedding", "engagement"],
    intensity: "medium",
    description: "Concentric magical ring animations",
  },
  {
    id: "meta-balls",
    name: "MetaBalls",
    source: "reactbits",
    category: "decoration",
    mood: ["playful", "whimsical"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Merging organic blob shapes",
  },
  {
    id: "ribbons",
    name: "Ribbons",
    source: "reactbits",
    category: "decoration",
    mood: ["romantic", "elegant"],
    eventTypes: ["wedding", "celebration", "engagement"],
    intensity: "medium",
    description: "Flowing ribbon streamers animation",
  },

  // ═══════════════════════════════════════════
  // NAV STYLES (6, custom) + DECORATIONS (kept)
  // ═══════════════════════════════════════════
  {
    id: "glass-dropdown",
    name: "GlassDropdown",
    source: "reactbits",
    category: "nav-style",
    mood: ["modern", "elegant"],
    eventTypes: "*",
    intensity: "medium",
    description: "Frosted glass dropdown with staggered reveals",
  },
  {
    id: "glass-slide",
    name: "GlassSlide",
    source: "reactbits",
    category: "nav-style",
    mood: ["modern", "elegant"],
    eventTypes: "*",
    intensity: "subtle",
    description: "Glass bar with spring-animated pill indicator",
  },
  {
    id: "glass-morph",
    name: "GlassMorph",
    source: "reactbits",
    category: "nav-style",
    mood: ["elegant", "dramatic"],
    eventTypes: ["wedding", "anniversary", "vow-renewal"],
    intensity: "medium",
    description: "Centered glass pill with chromatic shimmer border",
  },
  {
    id: "glow-nav",
    name: "GlowNav",
    source: "reactbits",
    category: "nav-style",
    mood: ["dramatic", "modern"],
    eventTypes: ["elopement", "celebration", "engagement"],
    intensity: "medium",
    description: "Dark nav with luminous glow orb on active item",
  },
  {
    id: "magnetic-hover",
    name: "MagneticHover",
    source: "reactbits",
    category: "nav-style",
    mood: ["modern", "playful"],
    eventTypes: "*",
    intensity: "subtle",
    description: "Items spring-scale on hover with magnetic feel",
  },
  {
    id: "minimal-fade",
    name: "MinimalFade",
    source: "reactbits",
    category: "nav-style",
    mood: ["elegant", "romantic"],
    eventTypes: ["wedding", "vow-renewal", "anniversary"],
    intensity: "subtle",
    description: "Ultra-clean nav with staggered fade-in",
  },
  {
    id: "lanyard",
    name: "Lanyard",
    source: "reactbits",
    category: "decoration",
    mood: ["playful", "whimsical"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Dangling lanyard badge with physics",
    disabled: true,
  },
  {
    id: "model-viewer",
    name: "ModelViewer",
    source: "reactbits",
    category: "decoration",
    mood: ["modern", "dramatic"],
    eventTypes: ["celebration"],
    intensity: "dramatic",
    description: "Interactive 3D model viewer component",
    disabled: true,
  },
];

export function getEffectsByCategory(category: EffectCategory): EffectEntry[] {
  return EFFECT_REGISTRY.filter((e) => e.category === category && !e.disabled);
}

export function getRecommended(
  category: EffectCategory,
  eventType: EventType,
): EffectEntry[] {
  return EFFECT_REGISTRY.filter(
    (e) =>
      e.category === category &&
      !e.disabled &&
      (e.eventTypes === "*" || e.eventTypes.includes(eventType)),
  );
}

export function getEffectById(id: string): EffectEntry | undefined {
  return EFFECT_REGISTRY.find((e) => e.id === id);
}
