import type { EffectEntry } from "./types";

export const DECORATION_EFFECTS: EffectEntry[] = [
  {
    id: "antigravity",
    name: "Antigravity",
    source: "reactbits",
    category: "decoration",
    mood: ["whimsical", "playful"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Elements float upward defying gravity",
    disabled: true,
  },
  {
    id: "electric-border",
    name: "ElectricBorder",
    source: "reactbits",
    category: "decoration",
    mood: ["dramatic", "modern"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Electric arcs along element borders",
  },
  {
    id: "laser-flow",
    name: "LaserFlow",
    source: "reactbits",
    category: "decoration",
    mood: ["modern", "dramatic"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Flowing laser beam animation along edges",
    disabled: true,
  },
  {
    id: "magic-rings",
    name: "MagicRings",
    source: "reactbits",
    category: "decoration",
    mood: ["whimsical", "romantic"],
    eventTypes: ["wedding", "engagement"],
    intensity: "medium",
    description: "Concentric magical ring animations",
    disabled: true,
  },
  {
    id: "meta-balls",
    name: "MetaBalls",
    source: "reactbits",
    category: "decoration",
    mood: ["playful", "whimsical"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Merging organic blob shapes",
  },
  {
    id: "ribbons",
    name: "Ribbons",
    source: "reactbits",
    category: "decoration",
    mood: ["romantic", "elegant"],
    eventTypes: ["wedding", "celebration", "engagement"],
    intensity: "medium",
    description: "Flowing ribbon streamers animation",
  },
  {
    id: "lanyard",
    name: "Lanyard",
    source: "reactbits",
    category: "decoration",
    mood: ["playful", "whimsical"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Dangling lanyard badge with physics",
    disabled: true,
  },
  {
    id: "model-viewer",
    name: "ModelViewer",
    source: "reactbits",
    category: "decoration",
    mood: ["modern", "dramatic"],
    eventTypes: ["celebration"],
    intensity: "dramatic",
    description: "Interactive 3D model viewer component",
    disabled: true,
  },
];
