import type { EffectEntry } from "./types";

export const NAV_EFFECTS: EffectEntry[] = [
  {
    id: "glass-dropdown",
    name: "GlassDropdown",
    source: "reactbits",
    category: "nav-style",
    mood: ["modern", "elegant"],
    eventTypes: "*",
    intensity: "medium",
    description: "Frosted glass dropdown with staggered reveals",
  },
  {
    id: "glass-slide",
    name: "GlassSlide",
    source: "reactbits",
    category: "nav-style",
    mood: ["modern", "elegant"],
    eventTypes: "*",
    intensity: "subtle",
    description: "Glass bar with spring-animated pill indicator",
  },
  {
    id: "glass-morph",
    name: "GlassMorph",
    source: "reactbits",
    category: "nav-style",
    mood: ["elegant", "dramatic"],
    eventTypes: ["wedding", "anniversary", "vow-renewal"],
    intensity: "medium",
    description: "Centered glass pill with chromatic shimmer border",
  },
  {
    id: "glow-nav",
    name: "GlowNav",
    source: "reactbits",
    category: "nav-style",
    mood: ["dramatic", "modern"],
    eventTypes: ["elopement", "celebration", "engagement"],
    intensity: "medium",
    description: "Dark nav with luminous glow orb on active item",
  },
  {
    id: "magnetic-hover",
    name: "MagneticHover",
    source: "reactbits",
    category: "nav-style",
    mood: ["modern", "playful"],
    eventTypes: "*",
    intensity: "subtle",
    description: "Items spring-scale on hover with magnetic feel",
  },
  {
    id: "minimal-fade",
    name: "MinimalFade",
    source: "reactbits",
    category: "nav-style",
    mood: ["elegant", "romantic"],
    eventTypes: ["wedding", "vow-renewal", "anniversary"],
    intensity: "subtle",
    description: "Ultra-clean nav with staggered fade-in",
  },
];
