import type { EffectEntry } from "./types";

export const TEXT_EFFECTS: EffectEntry[] = [
  {
    id: "fuzzy-text",
    name: "FuzzyText",
    source: "reactbits",
    category: "text",
    mood: ["whimsical", "playful"],
    eventTypes: ["engagement", "celebration"],
    intensity: "medium",
    description: "Text with fuzzy static distortion effect",
  },
  {
    id: "glitch-text",
    name: "GlitchText",
    source: "reactbits",
    category: "text",
    mood: ["modern", "dramatic"],
    eventTypes: ["celebration", "engagement"],
    intensity: "dramatic",
    description: "Text with digital glitch distortion",
  },
  {
    id: "gradient-text",
    name: "GradientText",
    source: "reactbits",
    category: "text",
    mood: ["elegant", "romantic"],
    eventTypes: ["wedding", "anniversary", "vow-renewal"],
    intensity: "subtle",
    description: "Animated gradient flowing through text",
  },
  {
    id: "shiny-text",
    name: "ShinyText",
    source: "reactbits",
    category: "text",
    mood: ["elegant", "playful"],
    eventTypes: ["anniversary", "engagement", "celebration"],
    intensity: "subtle",
    description: "Shimmer highlight sweeps across text",
  },
  {
    id: "text-pressure",
    name: "TextPressure",
    source: "reactbits",
    category: "text",
    mood: ["modern", "dramatic"],
    eventTypes: ["celebration", "engagement"],
    intensity: "medium",
    description: "Text weight responds to cursor proximity",
  },
  {
    id: "variable-proximity",
    name: "VariableProximity",
    source: "reactbits",
    category: "text",
    mood: ["modern", "playful"],
    eventTypes: ["celebration", "engagement"],
    intensity: "subtle",
    description: "Variable font axes shift based on cursor distance",
  },
];
